fgnt/meeteval

- meeteval/io/base.py
- meeteval/wer/utils.py
- meeteval/wer/wer/cp.py
- meeteval/wer/wer/time_constrained.py
- tests/test_time_constrained.py
Those hyp/ref, that got no ref/hyp assigned where ignored in the
estimation of the best mapping. Hence, it could happen (typically with
bad transcriptions), that the estimated mapping is not the best mapping.
Now the full cost_matrix is estimated and for over- and underestimation,
the mapping is also correct, when the transcriptions are bad.
Thanks to @popcornell for finding this bug.
> Bugfix: Mapping in cpwer was in special cases suboptimal

- meeteval/wer/matching/cy_mimo_matching.pyx
- meeteval/wer/matching/mimo_matching.h
- meeteval/wer/matching/mimo_matching.py
- meeteval/wer/wer/mimo.py
- tests/test_mimo_matching.py
The C++ implementation in this PR is easier to read and faster than the Cython implementation. This is due to a few small optimizations getting rid of indexing operations and multiplications. The overall speedup is about 3-6 on the benchmark from the publication. This PR does not change memory usage.
> Add a faster C++ Implementation of MIMO WER

- meeteval/wer/matching/orc_matching.py
- meeteval/wer/wer/cp.py
- setup.py
- tests/test_levenshtein.py
editdistance produces wrong results for long sequences (https://github.com/roy-ht/editdistance/pull/103) and the maintainer doesn't seem to be active. Use our impelmentation of the Levenshtein distance instead
> Remove editdistance dependency

- pyproject.toml
Allows the project to be built w/o the manual installation of `cython`.
> build: add `build-system` via `pyproject.toml`

- .bumpversion.cfg
- .github/workflows/release-pypi.yml
- .github/workflows/release.yml
- maintenance.md
- setup.py
Add a GitHub workflow for publishing on PyPI. The workflow gets executed when a release is created on GitHub.
Currently, only sdist is built since building wheels for a Cython package is tricky.
The workflow uses a "truested publisher" (https://docs.pypi.org/trusted-publishers/using-a-publisher/) to push the release to PyPI. This way, no credentials are stored in the GitHub repository.
> Add workflow file for PyPI sdist release

- README.md
I just checked this repo to see which paper to cite and saw that it is still the arxiv version. Maybe you want to update this to the ICASSP version?
> ICASSP reference in README

- meeteval/der/md_eval.py
The code failed in a corner case, where the summary DER from md-eval cannot be calculated from the values that are obtained per recording. This is caused by rounding effects of the printed per recording numbers. Hence, we cannot reproduce this behavior.
This PR weakens the checks, such the code can be executed in those cases. In the summary, we use the value, that is calculated by md-eval.
> Fix md-eval for corner case

- meeteval/der/__main__.py
- meeteval/der/api.py
- meeteval/der/md_eval.py
- meeteval/wer/__main__.py
- tests/test_cli.py
Adresses #62. The name is still up for discussion.
> Add argument to only evaluate single-speaker regions

- meeteval/__init__.py
- meeteval/viz/__init__.py
- meeteval/viz/__main__.py
- meeteval/viz/side_by_side_sync.html
- meeteval/viz/visualize.css
- meeteval/viz/visualize.js
- meeteval/viz/visualize.py
The viewAreas are now managed in a central location instead of in the local minimap objects. The central state is a single source of truth and eliminates much of the communication between plot objects. This has a few benefits:
- much shorter implementations for the minimaps (because the communication code is gone)
- reasoning about state changes is easier because everything is handled in a central location
- throttling is synchronized between plots and applied to both word filtering and plotting
- It is easier to determine which plots have to be updated, which results in significant speedups for viewing long recordings 
Additionally, functionality was added to synchronize plots in a side-by-side view.
> Centralize viewArea state in Visualization

- .github/workflows/pytest.yml
- README.md
- setup.py
- tests/test_docs.py
Extracts and runs code blocks in README.md.
Tests the output of print statements against the following comment lines, ignoring any whitespace.
Only executes python cells and parses STM cells. All other cells are not tested.
> Add testcase that runs code blocks in readme

- meeteval/viz/__main__.py
Reorders and groups columns from the same system. Numbers are now displayed with a monospaced font and aligned at the decimal dot. The sorting state is stored in the URL so that hitting the back button in the browser returns to the earlier state.
This is an example:
with the sort encoded like this in the URL: `.../index.html?sort=1&order=descending`
> Rework overview table

- README.md
- example_files/hyp.seglst.json
- example_files/hypA.stm
- example_files/hypB.stm
- example_files/refA.stm
- example_files/refB.stm
- meeteval/io/seglst.py
- meeteval/viz/__main__.py
- meeteval/wer/__main__.py
- meeteval/wer/api.py
- meeteval/wer/preprocess.py
- meeteval/wer/wer/cp.py
- meeteval/wer/wer/mimo.py
- meeteval/wer/wer/orc.py
- meeteval/wer/wer/siso.py
- meeteval/wer/wer/time_constrained.py
- meeteval/wer/wer/time_constrained_orc.py
- tests/test_docs.py
- tests/test_preprocess.py
- tests/test_time_constrained_orc_matching.py
Add functions for input preprocessing that are shared across WER functions. This removes some duplicate code (or code that was not exactly duplicated but did essentially the same thing).
This is also a preparation for adding the DI-cpWER and the greedy algorithm for the ORC-WER and DI-cpWER to prevent adding the same code there again.
Now, non-time-constrained WERs also compute self-overlap if timestamps are given.
> Unify preprocessing

- README.md
- doc/algorithms.md
- meeteval/wer/__main__.py
- meeteval/wer/api.py
- meeteval/wer/matching/cy_greedy_combination_matching.pyx
- meeteval/wer/matching/greedy_combination_matching.py
- meeteval/wer/preprocess.py
- meeteval/wer/wer/__init__.py
- meeteval/wer/wer/cp.py
- meeteval/wer/wer/orc.py
- meeteval/wer/wer/siso.py
- pyproject.toml
- setup.py
- tests/test_cli.py
- tests/test_greedy_combination_matching.py
This PR adds the core greedy algorithm and the wrappers for ORC WER. I will add other pull requests for the time-constrained greedy algorithm and the DI-cpWER when this is merged.
I named it "greedy combination matching", similar to the "optimal combination matching" acronym from the ORC WER. Given this naming, I'm unsure if the name "greedy ORC-WER" fits well because it mixes the terms "greedy" and "optimal". But, at the same time, the term ORC-WER is already known, and greedy ORC seems clearer to me.
I did not use "reference" and "hypothesis" but "segments" and "streams" so that the core code can be used for both ORC-WER and DI-cpWER without name conflicts.
> Add greedy orc WER

- meeteval/viz/__main__.py
- meeteval/viz/visualize.css
- meeteval/viz/visualize.js
- meeteval/viz/visualize.py
Fixes the (long broken) warning for self-overlap in the UI and splits a speaker column into multiple sub-columns if utterances of the same speaker overlap.
This is an example of the overlap visualization in the details plot
This way of visualization is not pretty since the lines connecting matching words overlap, but it shows all relevant information and is much better than the previous behavior.
I also cleaned up the code a little:
- Removed the partial support for multiple hypothesis in the same visualization in favor of the synchronized side-by-side view
- The horizontal positions of the utterances are now precomputed
- The WER displayed in the visualization now matches the WER computed by the CLI tool exactly
- It is now easier to add assignment algorithms, like DI-cp, in the future
- …
> Visualize speaker self-overlaps in the details plot

- .gitignore
- meeteval/viz/visualize.css
- meeteval/viz/visualize.js
- meeteval/viz/visualize.py
- scripts/build_pyodide_wheel.sh
- Adds buttons to jump to the previous/next match to the search box
- Remove internal keys from the details view
- Display the original stream label from the input files (before applying the assignment) in the details table
- Add a timeout for opening the tooltip to prevent opening it accidentally. This is especially useful for the large details tooltip that may cover a large area of the plots
- Make the audio player and copy button smaller in the collapsed details view so that the views don't jump when an audio player is displayed
- Animate drastic view changes, like jumping to the next search match
- Improve rendering of the begin time and end time markers
- Improve rendering of search highlights
- Move view area to segment/utterance on double click
> Various minor improvements to the visualization

- meeteval/io/seglst.py
- meeteval/wer/wer/orc.py
- tests/test_docs.py
- tests/test_time_constrained_orc_matching.py
Fix the ORC assignment for empty segments.
This has no effect on the WER, only on the assignment, which sometimes had the wrong length when empty segments (`words=''`) were present.
> Fix orc assignment empty segments

- meeteval/wer/wer/orc.py
- meeteval/wer/wer/time_constrained.py
- tests/test_time_constrained_orc_matching.py
The fix in #90 introduced another issue which is fixed in this PR.
> Fix the ORC assignment again

- meeteval/der/__main__.py
- meeteval/wer/__main__.py
Print a one-line summary of the WER, in KALDI style:
```
$ meeteval-wer tcpwer -r example_files/ref.stm -h example_files/hyp.stm --collar 5
INFO Wrote: /home/neumann/workspace/python/meeteval/example_files/hyp_tcpwer_per_reco.json
INFO Wrote: /home/neumann/workspace/python/meeteval/example_files/hyp_tcpwer.json
INFO %tcpWER: 27.17% [ 25 / 92, 8 ins, 15 del, 2 sub ]
```
> Print wer summary

- meeteval/wer/__main__.py
- meeteval/wer/api.py
- requirements.txt
I changed the if statement in the source code to a class to have all code together that belongs to the normalizer.
The chimeX normalizers have a runtime dependency of chime-utils
> add more normalizers, "lower,rm([^a-z0-9 ])" and chime6/7/8

- meeteval/der/__main__.py
- meeteval/der/md_eval.py
- meeteval/viz/__main__.py
- meeteval/viz/side_by_side_sync.html
- meeteval/viz/visualize.css
- meeteval/viz/visualize.js
- meeteval/viz/visualize.py
- meeteval/wer/__main__.py
- setup.py
- tests/test_cli.py
- tests/test_viz.py
- Add all supported assignment options to the visualization (cp, tcp, orc, tcorc, greedy_dicp, ...)
- Add entrypoint `meeteval-viz`
- Add option to load a precomputed assignment from a `*_per_reco.json` file (or an `ErrorRate` object in the Python interface)
- Automatically increase the number of minimaps for large examples
- Show current playhead position in details plot on playback
> Improve Visualization

- README.md
- meeteval/der/__main__.py
- meeteval/der/api.py
- meeteval/der/dscore.py
- meeteval/der/md_eval.py
- setup.py
- tests/test_cli.py
In #97 it was mentioned, that `dscore` calculates the `DER` differently to `md-eval-22.pl`, if no uem file is given:
- `md-eval-22.pl`: Choose the scoring region, such that it starts with the first reference and ends with the last reference.
- `dscore`:  Score everything. Implementation: Create an uem with the scoring regions to be the smallest start in ref and hyp and the end is the last time in ref and hyp.
Additional bugfix:
- `md-eval-22.pl` ignores the uem files, if the filenames/session_ids contain dots
- `dscore` fails with a lengthy error
ToDO:
> Add dscore like DER

- meeteval/wer/__main__.py
- tests/test_cli.py
The default for collar was zero, but in most cases, it yields an unrealistic WER. I had it a few times, that I called tcpwer and was confused by the high WER.
Added 5 seconds to the help text, since it is our recommented value.
> change collar to be required for time constrained WERs

- meeteval/io/seglst.py
While checking the `apply_multi_file` function in `meeteval/io/seglst.py`, I noticed `h_minus_r` was a list used for checking if keys are in it during a dictionary comprehension. List lookups are O(N), so I refactored it to use a set for faster O(1) lookups.
Now, `h_minus_r_set` holds the set of keys in `hypothesis` not in `reference`, and the comprehension uses it to filter keys. I kept `h_minus_r` as a list for logging (like showing `h_minus_r[:5]`), so all output and behavior stay exactly the same. It's not a huge optimization, but it makes key checks a bit more efficient, especially if `h_minus_r` has many keys.
> refactor: using h_minus_r_set to lookups

- meeteval/io/smart.py
- meeteval/wer/__main__.py
- meeteval/wer/api.py
- meeteval/wer/normalizer.py
- tests/test_cli.py
Adds a command `meeteval-wer normalize` that normalizes the words in any input file according to one normalizer and dumps it in the same or any other format.
```console
$ meeteval-wer normalize example_files/ref.stm --normalizer 'chime8' -o -
recordingA 1 Alice 1 1 effort made was a lot i know you are busy we need to make the new version clean
recordingA 1 Bob 1 2 strategic staircase we need a paradigm shift
recordingA 1 Bob 2 3
recordingA 1 Alice 2 3 pipeline bob called an all hands this afternoon
recordingB 1 Alice 3 4 hop on the bandwagon let us schedule a standup during the sprint to review our kpis
recordingB 1 Alice 4 5 hop on the bandwagon let us schedule a standup during the sprint to review our kpis
recordingA 1 Alice 5 6 organic growth what do you feel you would bring to the …
```
> Add meeteval-wer normalize CLI command

- example_files/hyp_siso.stm
- example_files/ref_siso.stm
- meeteval/io/seglst.py
- meeteval/wer/__main__.py
- meeteval/wer/api.py
- meeteval/wer/wer/siso.py
- tests/test_cli.py
Closes #110.
Add the SISO WER as `meeteval.wer.sisower` to the high-level Python api.
I named it `sisower` instead of `wer` to avoid conflicts with the module `meeteval.wer.wer`. I didn't change the CLI command name, it is still just `wer`.
The new API function now also supports STM and SegLST files when the file names are unique. Previously, only keyed text files were supported. This was done to avoid accidentally calling the SISO WER when you wanted to compute, e.g., the cpwer. But I now think that it is very unlikely to have unique filenames / session_ids when you don't want to compute the SISO WER.
> Add SISO WER to high-level Python api

- meeteval/viz/visualize.py
- tests/test_viz.py
Fix the mismatch between shown WER and alignment for corner cases of time constraint visualization.
The shown WER uses the point estimates for hyp (same as cli default), but the alignment calculation didn't use the point estimates.
This has only an effect for time constraint WERs and is only noticeable, when the time unit in the input files is not second,
e.g., a collar of 5 samples is far to low, while a collar of 5 seconds is a good choice, where the issue is barely noticeable.
How can this be observed:
In the tooltip to the WER, the count column is correct for the WER, but the speaker statistics reflect the alignment.
When there is a mismatch, it indicates, that some correct/substitution assignments are at the edge of the collar.
Should we add an assert to the code, that the statistics …
> Fix that the alignment calculation for the visualization didn't use point estimates

- .github/workflows/noneeditable.yml
- .github/workflows/pytest.yml
- meeteval/io/smart.py
- meeteval/viz/__main__.py
- meeteval/viz/overview_table.py
- meeteval/viz/visualize.py
- setup.py
- tests/test_cli.py
- tests/test_di_cp.py
- tests/test_docs.py
- tests/test_io_converters.py
- tests/test_viz.py
The added options enable compiling MeetEval on Windows.
The compilers on Windows and Linux are not compatible, so we have to switch compiler options.
> Add compiler options for Windows

- meeteval/der/md_eval.py
- meeteval/viz/visualize.py
- meeteval/wer/__main__.py
- meeteval/wer/wer/cp.py
- meeteval/wer/wer/di_cp.py
- meeteval/wer/wer/error_rate.py
- meeteval/wer/wer/mimo.py
- meeteval/wer/wer/orc.py
- meeteval/wer/wer/time_constrained.py
- tests/test_error_rate.py
Adds a key `"type"` to serialized error rates. This fixes ambiguous cases where saved results from DI-cpWER and ORC-WER could not be discriminated, and makes identification easier from the files alone.
```py
In [1]: from meeteval.wer.wer.orc import OrcErrorRate
In [2]: from meeteval.wer.wer.error_rate import ErrorRate
In [3]: er = OrcErrorRate.zero()
In [4]: serialized = er.asdict()
In [5]: serialized
Out[5]:
{'error_rate': 0,
'errors': 0,
'length': 0,
'insertions': 0,
'deletions': 0,
'substitutions': 0,
'reference_self_overlap': None,
'hypothesis_self_overlap': None,
'assignment': (),
'type': 'orc-error-rate'}
In [6]: ErrorRate.from_dict(serialized)
Out[6]: OrcErrorRate(error_rate=0, errors=0, length=0, insertions=0, deletions=0, substitutions=0, assignment=())
```
The old heuristics for …
> Add "type" identifier to error rate serialization

- meeteval/der/md_eval.py
Update `md_eval_22` with the following:
- Make the check that the average across the individual examples matches the overall reported error rate ("ALL") more permissive. Fixes #121 
- Call md-eval-22 with the `-a f` option to obtain per-session results with a single call to `md-eval-22.pl`
> Md eval 22
